version: '3'
services:
  service-system-eureka:
    container_name: service-system-eureka
    image: redlead/service-system-eureka:latest
    ports:
      - 8761:8761
    networks:
      - spring-cloud-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  service-system-api-gateway:
    container_name: service-system-api-gateway
    image: redlead/service-system-api-gateway:latest
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_URI=http://service-system-eureka:8761/eureka
  service-product:
    container_name: service-product
    image: redlead/service-product
    networks:
      - spring-cloud-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_URI=http://service-system-eureka:8761/eureka
    depends_on:
      - service-system-eureka
  service-client:
    container_name: service-client
    image: redlead/service-client
    networks:
      - spring-cloud-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_URI=http://service-system-eureka:8761/eureka
    depends_on:
      - service-system-eureka
networks:
  spring-cloud-network:
    driver: bridge